spring:
  application:
    name: doodle-test

datasource:
  primer: "classpath:polls.json"
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/test


server:
  port: 9000

#Logging configuration
logging.level:
  org.springframework.data.mongodb.core.ReactiveMongoTemplate:  DEBUG